FROM python:3.12-slim

WORKDIR /app

# Copy requirements.txt into the image
COPY requirements-dev.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements-dev.txt

# Copy your source code
COPY . .

# Default command
CMD ["pytest", "-v", "--testdox"]